version: '3.7'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    restart: always
    build: .
    command: gunicorn --bind=0.0.0.0:8000 app:app
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      postgres:
        condition: service_healthy
  nginx:
    build:
      context: .
      dockerfile: ngnix.dockerfile
    ports:
      - 80:80
    depends_on:
      - app
