version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - $HOME/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
